-- Criando a tabela USUARIO
CREATE TABLE USUARIO (
    COD_USUARIO VARCHAR(25) PRIMARY KEY, -- Chave primária
    MATRICULA VARCHAR(45) NOT NULL,
    NIVEL INT NOT NULL,
    SENHA VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(45) NOT NULL,
    CARGO VARCHAR(45) NOT NULL -- Corrigido campo vazio
);

-- Criando a tabela CLIENTE
CREATE TABLE CLIENTE (
    COD_CLIENTE INT PRIMARY KEY AUTO_INCREMENT, -- ID automático
    NOME VARCHAR(30) NOT NULL,
    TELEFONE VARCHAR(30) NOT NULL,
    ENDERECO VARCHAR(45) NOT NULL
);
